# Generated by Django 4.0.3 on 2022-04-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rulebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready', models.BooleanField()),
                ('title', models.CharField(max_length=32)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='rulebooks/thumbnails')),
                ('description', models.TextField()),
                ('link_to_page_rules', models.CharField(max_length=128)),
                ('link_original', models.CharField(blank=True, max_length=128, null=True)),
                ('link_ita', models.CharField(blank=True, max_length=128, null=True)),
                ('link_amazon', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rulebook_additional_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=32)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='rulebooks.rulebook')),
            ],
        ),
    ]
