# Generated by Django 4.0.2 on 2022-03-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rulebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games_cover')),
                ('link_original', models.CharField(blank=True, max_length=128, null=True)),
                ('link_ita', models.CharField(blank=True, max_length=128, null=True)),
                ('file_PDF', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
