# Generated by Django 4.0.2 on 2022-03-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rulebooks',
            new_name='Rulebook',
        ),
    ]
