# Generated by Django 4.0.2 on 2022-03-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0002_rename_rulebooks_rulebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebook',
            name='description',
            field=models.TextField(default='Placeholder'),
            preserve_default=False,
        ),
    ]
