# Generated by Django 4.0.3 on 2022-04-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0003_rulebook_additional_url_link_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulebook_additional_url',
            old_name='Link_type',
            new_name='link_type',
        ),
    ]
