# Generated by Django 4.0.2 on 2022-03-31 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0004_alter_rulebook_thumbnail_rulebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulebook_url',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='rulebooks.rulebook'),
        ),
    ]
