# Generated by Django 4.0.3 on 2022-04-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0004_rename_link_type_rulebook_additional_url_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulebook_additional_url',
            name='link_type',
            field=models.CharField(choices=[('GEN', 'General'), ('VID', 'Video'), ('FIL', 'File'), ('PDF', 'Pdf')], default='GEN', max_length=3),
        ),
    ]
