# Generated by Django 4.0.3 on 2022-04-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0005_alter_rulebook_additional_url_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebook_additional_url',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
