# Generated by Django 4.0.2 on 2022-03-31 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0005_alter_rulebook_url_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=16)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rulebook',
            name='test_url',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, related_name='test', to='rulebooks.test_url'),
            preserve_default=False,
        ),
    ]
