# Generated by Django 4.0.2 on 2022-03-31 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0006_test_url_rulebook_test_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulebook',
            name='test_url',
        ),
    ]
