# Generated by Django 4.0.3 on 2022-04-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0006_rulebook_additional_url_is_official'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulebook_additional_url',
            name='is_official',
        ),
        migrations.AddField(
            model_name='rulebook',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
