# Generated by Django 4.0.2 on 2022-03-31 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0007_remove_rulebook_test_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebook',
            name='test_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='rulebooks.test_url'),
        ),
    ]
