# Generated by Django 4.0.2 on 2022-03-31 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0008_rulebook_test_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulebook',
            old_name='test_url',
            new_name='test',
        ),
    ]
