# Generated by Django 4.0.2 on 2022-03-31 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0009_rename_test_url_rulebook_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulebook',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='rulebooks.test_url'),
        ),
    ]
