# Generated by Django 4.0.2 on 2022-03-31 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0010_alter_rulebook_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulebook',
            name='test',
        ),
        migrations.DeleteModel(
            name='test_url',
        ),
    ]
