# Generated by Django 4.0.2 on 2022-03-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0011_remove_rulebook_test_delete_test_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulebook_url',
            name='url_name',
            field=models.CharField(max_length=32),
        ),
    ]
