# Generated by Django 4.0.2 on 2022-04-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0012_alter_rulebook_url_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebook',
            name='link_to_rules',
            field=models.CharField(default='Placeholder', max_length=128),
            preserve_default=False,
        ),
    ]
