# Generated by Django 4.0.2 on 2022-04-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0013_rulebook_link_to_rules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rulebook_url',
            new_name='Rulebook_additional_url',
        ),
        migrations.RenameField(
            model_name='rulebook',
            old_name='link_to_rules',
            new_name='link_to_page_rules',
        ),
        migrations.RemoveField(
            model_name='rulebook',
            name='file_PDF',
        ),
    ]
