# Generated by Django 4.0.2 on 2022-04-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0014_rename_rulebook_url_rulebook_additional_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebook',
            name='link_amazon',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
