# Generated by Django 4.0.2 on 2022-04-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0015_rulebook_link_amazon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulebook',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='rulebooks/thumbnails'),
        ),
    ]
