# Generated by Django 4.0.2 on 2022-04-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulebooks', '0016_alter_rulebook_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebook',
            name='is_ready',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
