# Generated by Django 4.0.3 on 2022-04-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automa_boardgames',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
