# Generated by Django 4.0.2 on 2022-03-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boardgames_with_solo_mode',
            new_name='Automa_boardgames',
        ),
    ]
