# Generated by Django 4.0.2 on 2022-03-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automa', '0002_rename_boardgames_with_solo_mode_automa_boardgames'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='automa_boardgames',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AddField(
            model_name='automa_boardgames',
            name='tags',
            field=models.ManyToManyField(related_name='boardgames', to='automa.Tags'),
        ),
    ]
