# Generated by Django 4.0.2 on 2022-03-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automa', '0003_tags_alter_automa_boardgames_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automa_boardgames',
            name='isAutoma',
        ),
        migrations.AddField(
            model_name='automa_boardgames',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games_cover'),
        ),
    ]
