# Generated by Django 4.0.2 on 2022-03-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automa', '0005_automa_boardgames_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automa_boardgames',
            name='size',
            field=models.CharField(default='X', max_length=8),
        ),
    ]
