# Generated by Django 4.0.2 on 2022-03-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automa', '0007_alter_automa_boardgames_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automa_boardgames',
            name='size',
        ),
    ]
