# Generated by Django 4.0.3 on 2022-04-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automa', '0012_alter_automa_boardgames_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automa_boardgames',
            name='short_title',
            field=models.CharField(default='shorttitle', max_length=32),
        ),
    ]
