# Generated by Django 4.0.3 on 2022-04-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automa', '0013_alter_automa_boardgames_short_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automa_boardgames',
            name='short_title',
        ),
        migrations.AddField(
            model_name='automa_boardgames',
            name='short',
            field=models.CharField(default=models.CharField(max_length=32), max_length=32),
        ),
    ]
