# Generated by Django 4.0.3 on 2022-04-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automa', '0015_rename_short_automa_boardgames_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automa_boardgames',
            name='short_title',
            field=models.CharField(max_length=32),
        ),
    ]
